name: govulncheck

on:
  workflow_dispatch:
  schedule:
    - cron: "33 3 * * MON,THU" # Monday & Thursday at 03:33 UTC

permissions:
  contents: read

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09  # v5.1.0
        with:
          persist-credentials: false

      - uses: golang/govulncheck-action@032d45514ae346b1db93c04b0c90b841c370344f  # v1.1.0
        with:
          go-version-file: go.mod
          go-version-input: ''
